### ISSUE TITLE
} expected (9999) when using @property & @scroll-timeline syntax

### ISSUE THREAD

**Issue by calinoracation** [microsoft/typescript-styled-plugin#150]
I'm getting similar error messages as in others, but with the following syntaxes using `@property` & `@scroll-timeline`. 

cc: @lencioni 

```css
@property --radius {
  syntax: '<length>';
  inherits: false;
  initial-value: 20px;
}
```
<img width="420" alt="Screen Shot 2021-09-28 at 1 40 24 PM" src="https://user-images.githubusercontent.com/23196205/135162397-15494e2f-09c4-4916-b699-115295695b4a.png">

and also for the scroll-timeline syntax:

```css
@scroll-timeline collision-timeline {
  source: selector(#container);
  orientation: block;
  scroll-offsets: 200px, 300px;
}
```
